FORMAT: 1A
HOST: http://www.google.com

# regioner og kundeavis
Hver kjede kan ha en eller flere navngitte samlinger butikker. 
Disse kalles *regioner* og har teknisk sett ingen binding til organisatoriske eller geografiske regionsbegreper (men kan overlappe disse). 


## Regioner [/regions/{chainid}]
### list ut alle regioner [GET]

+ Parameters
    + chainid (required, number, `1100`) ... `kjede-id`      

+ Response 200 (application/json)

    
        [{
          "id": 1, 
          "title": "Oslofjord",
          "magazines" : 
            [
                "magazine" : {
                    "id" : 123
                    "resource" : "http://viewer.zmags.com/publication/68d27aa3#/68d27aa3/1",
                    "from" : date,
                    "to" : date
                },
                "magazine" : {
                    "id" : 123
                    "resource" : "http://viewer.zmags.com/publication/68d27aa3#/68d27aa3/1",
                    "from" : date,
                    "to" : date
                }
            ],
          "stores": [
            {
                "store": { 
                    "Id":"7080001315467",
                    "name":"Kiwi 069 Koppang"}
                    },
                {"store":{"Id":"7080003309907","name":"Kiwi 735 Spangereid"}},{"store":{"Id":"7080003528988","name":"Kiwi 737 Mandal"}}]
        }, {
          "id": 2, 
          "title": "Øst",
          "magazines" : "http://viewer.zmags.com/publication/68d27aa3#/68d27aa3/1"
          "stores": [{"store":{"Id":"7080000960682","name":"Kiwi 711 Vanse"}},{"store":{"Id":"7080000356812","name":"Kiwi 766 Farsund"}},{"store":{"Id":"7080001125523","name":"Kiwi 796 Vigeland"}},{"store":{"Id":"7080001201432","name":"Kiwi 731 Lyngdal"}},{"store":{"Id":"7080000960590","name":"Kiwi 702 Langenes"}},{"store":{"Id":"7080001227074","name":"Kiwi 734 Flekkerøy"}},{"store":{"Id":"7080000960699","name":"Kiwi 712 Tangvall"}},{"store":{"Id":"7080001255107","name":"Kiwi 738 Alleen Senter"}},{"store":{"Id":"7080001208158","name":"Kiwi 797 Ytre Vågsbygd"}},{"store":{"Id":"7080000876426","name":"Kiwi 701 Vågsbygd Senter"}}],],
        }]

### Opprett en ny region [POST]
+ Request (application/json)

        { "title": "Nord" }

+ Response 201 (application/json)

        { "id": 3, "title": "Nord", "magazine" : "", "stores" : [] }

## Region [/regions/{chainid}/?regionid={id}]
Enkel region med alle egenskaper

+ Parameters
    + chainid (required, number, `1100`) ... `kjedeid`      
    + regionid (required, number, `1`) ... `id` til aktuell region
    

### Hent en region [GET]
+ Response 200 (application/json)

    + Header

            Last-modified: ddmmåå

    + Body
    
            { "id": 2, "title": "Øst", "magazine" : "http://viewer.zmags.com/publication/68d27aa3#/68d27aa3/1", "stores": [20,21,22,23,24,25,26,27,28,29], }

### Slett en region [DELETE]
+ Response 204

## Kundeavis [/magazine/{chainid}/]
+ Response 200 (application/json)
{ "url": "http://viewer.zmags.com/publication/68d27aa3#/68d27aa3/1" }


##
